# Generated by Django 4.1.7 on 2023-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rute',
            name='image',
            field=models.FilePathField(path='/rute/img'),
        ),
    ]
