# Generated by Django 4.1.7 on 2023-03-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rute', '0002_alter_rute_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rute',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
